#!/bin/sh

bspc config normal_border_color '@wm_border_unfocus@'
bspc config active_border_color '@accent@'
bspc config focused_border_color '@wm_border_focus@'
bspc config presel_feedback_color '@wm_border_focus@'

bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity first_child

bspc config focus_follows_pointer true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding @top_monocle_padding@
bspc config right_monocle_padding @right_monocle_padding@
bspc config bottom_monocle_padding @bottom_monocle_padding@
bspc config left_monocle_padding @left_monocle_padding@

bspc config window_gap @window_gap@
bspc config border_width @border_width@

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a firefox-nightly state=tiled
bspc rule -a Steam follow=no
bspc rule -a Zathura state=tiled
bspc rule -a bluetoothctl state=floating
bspc rule -a nmtui state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a fcitx5-config-qt state=floating
