#!/bin/sh

bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity first_child

bspc config window_gap @window_gap@

bspc config border_width @border_width@
bspc config focused_border_color '@wm_border_focus@'
bspc config active_border_color '@fg@'
bspc config normal_border_color '@wm_border_unfocus@'

bspc config presel_feedback_color '@wm_border_focus@'

bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config top_monocle_padding @monocle_padding@
bspc config bottom_monocle_padding @monocle_padding@
bspc config left_monocle_padding @monocle_padding@
bspc config right_monocle_padding @monocle_padding@

@rules@
