#!/bin/sh

bspc config border_width 0
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding @monocle_padding@
bspc config bottom_monocle_padding @monocle_padding@
bspc config left_monocle_padding @monocle_padding@
bspc config right_monocle_padding @monocle_padding@
bspc config presel_feedback_color '@brorange@'
bspc config split_ratio 0.62
bspc config window_gap @window_gap@
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc rule --add Steam follow=no
bspc rule --add Zathura state=tiled
