#!/bin/sh

btops &

bspc config border_width 0
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config presel_feedback_color '#f75341'  # srcery brred
bspc config split_ratio 0.62
bspc config window_gap @window_gap@
